### PR TITLE
Conflict target specification

### PR DESCRIPTION
**Pull request by rimmington**
This **breaking** change requires users to specify a [conflict_target](https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT) in ON CONFLICT DO UPDATE clauses. Both the Postgres documentation and some ad-hoc testing suggest that this is required, or at least I haven't found a case where it's not a syntax error.

Happy for nitpicking, I'm not entirely satisfied with some of the type variable naming in particular.

### CODE REVIEW

**Comment by rimmington** [comment]
PostgreSQL lets you specify a primary key or unique constraint (both "unique index constraints") by listing the columns the index contains rather than the constraint name. I think it's for compatibility across schema changes; from the documentation:

> It is often preferable to use unique index inference rather than naming a constraint directly using ON CONFLICT ON CONSTRAINT constraint_name. Inference will continue to work correctly when the underlying index is replaced by another more or less equivalent index in an overlapping way, for example when using CREATE UNIQUE INDEX ... CONCURRENTLY before dropping the index being replaced.

The `excluded` "virtual" table contains the rows that were proposed for insertion by the insert statement but couldn't be inserted because they violated the constraint. I think the idea is then you can merge the values you attempted to insert with those already in the database. `excluded` is a hardcoded/non-configurable name from PostgreSQL.

Perhaps some of the above detail should be included in the Haddocks?

(Disclaimer: I'm just learning this myself, so I may be wrong in some detail or terminology)

**Comment by echatav** [comment]
I think I get it. Squeal doesn't yet support indexes. I'd want to track them in the schema and hence type check that the keys are indexed as well as having a [`Uniquely`](https://github.com/morphismtech/squeal/blob/master/squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs#L282) constraint. Maybe we should leave the `UniqueIndexOn` constructor for a full index support issue?

For `excluded` stuff, that seems pretty advanced. Is this a use case you need? I guess it corresponds to `Data.Map.insertWith`. I think you could universally quantify the "existing" table name in a fRankeNtype. Then you could make an `IsLabel` instance for that fRankeNtype for columns of the "existing" table. We'd need to test that it actually worked as expected.

**Comment by rimmington** [comment]
To clarify: I believe that both PKs and Unique constraints are backed by indexes for enforcement, hence the phrase "unique index"; I don't know if you can specify an arbitrary index. For example, if you have a table

```
some_table (name varchar, CONSTRAINT some_table_pk PRIMARY KEY (name))
```

you could specify the constraint `some_table_pk` via either `OnConstraint #some_table_pk` or `UniqueIndexOn #name`.

I did consider making a check for a relevant constraint in the schema type when using `UniqueIndexOn`, but it seemed contrary to the intent of the feature specified in the PostgreSQL documentation. I don't mind if it's dropped for a later, more complete solution; I don't have any use case for it.

On the second point, I think `insertWith` is an apt comparison. It seems you need to explicitly quantify the column names with `excluded` or `existing`/some-other-table-alias or you'll get a column ambiguity error (hence the commit message "remove ambiguity ..."). Since that's the case I went ahead and supported `excluded`. Hard-coding `existing` just seemed the simplest approach, especially since, if you have a table named `excluded`, you *must* specify an alias or PostgreSQL will always pick the special/virtual `excluded` table and you can't access the existing values.

**Comment by rimmington** [comment]
I think I misunderstood your second point: are you suggesting something like `instance (Has column columns ty) => IsLabel (Expression schema '[table ::: columns, "excluded" ::: columns] Ungrouped params ty)` so you can refer to the existing values without quantification? That sounds reasonable, and a nice way to hide the `excluded` stuff from users who don't care about it. I'm just not sure how to get that to work alongside the existing `instance (HasUnique table from columns, Has column columns ty) => IsLabel column (Expression schema from Ungrouped params ty)`, since I expect changing `from` to `'[table ::: columns]` will end up introducing some type ambiguity errors.

**Comment by rimmington** [comment]
Also I just found out that you can't specify an FK constraint in an ON CONSTRAINT (`constraint in ON CONFLICT clause has no associated index`), so `Has constraintName constraints constraint` on `OnConstraint` is insufficient.

**Comment by echatav** [comment]
Perhaps we should break it into two constructors, `OnConflictDoUpdate` and `OnConflictDoUpdateWith`?

```Haskell
data ConflictClause
   (schema :: SchemaType)
   (table :: TableType)
     OnConflictDoNothing :: ConflictClause schema table params
     OnConflictDoUpdate
       :: (row ~ TableToRow table, columns ~ TableToColumns table)
       => ConflictTarget table
       -> (forall t. NP (Aliased (ColumnValue schema '[t ::: row] params)) columns
       -> [forall t. Condition schema '[t ::: row] 'Ungrouped params]
       -> ConflictClause schema table params
     OnConflictDoUpdateWith
       :: (row ~ TableToRow table, columns ~ TableToColumns table)
       => ConflictTarget table
       -> NP (Aliased (ColumnValue schema '["existing" ::: row, "excluded" ::: row] params)) columns
       -> [Condition schema '["included" ::: row, "excluded" ::: row] 'Ungrouped params]
       -> ConflictClause schema table params
```

**Comment by rimmington** [comment]
Regarding that `OnConflictDoUpdate`: neither the RHS of a SET nor any part of the WHERE can mention a column name unqualified without an ambiguity error, and I'm not sure how you could "inject" a table name (eg `included`) into the Aliased instance without infecting every use of column names in expressions.

(For the avoidance of doubt, I like the idea of hiding these table names unless you need them, I'm still trying to figure out how to get it to work)

**Comment by echatav** [comment]
Hopefully the changes here were included in #78 but I didn't included unique index stuff yet (because no index support yet)

**Pull request closed without merging**
