### PR TITLE
Added Comments to Definition

### PR DESCRIPTION
**Pull request by SamuelSchlesinger**
Added comments on tables, types, views, indices, and functions. One other thing we could add is comments on individual columns, or unsafe comments, but I didn't feel confident about how to do those things in an ergonomically good way.

### CODE REVIEW

**Comment by echatav** [comment]
Awesome! I didn't even know about `COMMENT`. As we discussed, look into how hard it would be to add `COMMENT ON COLUMN` the hard way by generalizing `QualifiedAlias` to something like

```Haskell
data Qualified
  (expr :: k -> Type)
  (q :: Symbol)
  (x :: k) where
  Qualified
    :: Alias q
    -> expr x
    -> Qualified expr q x
```

And getting the right `IsLabel` and `IsQualified` instances with expected behavior for the `public` schema and "double dotting", `sch ! tab ! col`. Have fun thinking about non-associativity or associativity of `!`.

**Comment by echatav** [comment]
Hmmm, association concerns are leading me to think this is a better datatype:

```Haskell
data Qualified (q :: Type) (a :: Symbol) where
  Qualified :: q -> Qualified q a
```

Then a `QualifiedAlias sch tab` becomes a `Qualified (Alias sch) tab` and you can define a `Qualified (Qualified (Alias sch) tab) col` and left associate `!`.

**Comment by echatav** [comment]
Lol, `Qualified` is just a kind specific version of `K` (generics-sop), `Const` (base), `Constant`...maaaaybe doesn't need yet another synonym.

**Comment by SamuelSchlesinger** [comment]
I think the least invasive way of doing this is what is in the second commit in this PR. I don't think its worth the churn cost to the ergonomics of the rest of the library to do it in one of the more complex ways you had suggested.

**Comment by SamuelSchlesinger** [comment]
One note is that this `commentOnConstraint` is perhaps less general than `SQL`s... I do not believe it will allow you to comment on a constraint which was defined in a `'Table` definition.

**Pull request merged**
