### PR TITLE
parameter check

### PR DESCRIPTION
**Pull request by echatav**
I wish there was a way to do this at the type level, but I cannot think of any. Right now, Squeal doesn't stop you from writing queries that don't use all of their parameters, even though this is a SQL error. Moreover, the SQL error itself is not so helpful.
```
*** Exception: PQException {sqlExecStatus = FatalError, sqlStateCode = Just "42P18", sqlErrorMessage = Just "ERROR:  could not determine data type of parameter $2\n"}
```
I'm not sure that this is any better though. But putting it up for some comments.

### CODE REVIEW

**Comment by echatav** [comment]
not tested yet...probably won't merge...anyone have a better idea how to handle this?

**Comment by echatav** [comment]
related to #94

**Comment by ilyakooo0** [comment]
If I understand the problem correctly, why not collect all type-level `Nat`s into some implementation of a set (type-level list) and make sure it contains all elements from `1` to `Length set`?

**Comment by echatav** [comment]
@ilyakooo0 I encourage you to try and see what problems you run into. But to preview, let's say you have the expression `param @1` and the expression `param @2` and you want to add them, `param @1 + param @2`. The first expression should have only `'[1]` in it's collection and the second should have `'[2]`, but their sum should have `'[1,2]`. Now that will break the `Num` typeclass since `(+) :: Num n => n -> n -> n` all three have the _same_ type. So ok, you'll have to replace using `Num` with new operators like `(.+)`. This is at least doable for binary operations or anything with a fixed number of inputs, but what about operations that take lists of inputs like `coalesce`? So, at least naively this doesn't work so well.

**Comment by echatav** [comment]
Giving this a bit more thought, let's pay closer attention to the error message:
```
*** "ERROR:  could not determine data type of parameter $2\n"
```
It's _not_ complaining about not using all the parameters. So I checked and in fact, you _can_ execute queries that don't know their parameters _as long as_ Postgres can determine the types of all the parameters. The way this is done Is by attaching an `Oid` to each parameter. Heretofore, I attached `LibPQ.invalidOid` which is `0`. Then to help Postgres, Squeal attaches types to the parameters, e.g. `($1 :: bool)`, either explicitly like `parameter @1 bool` or by using `PGTyped` to infer the type if possible in e.g. `param @1`. But that obviously _doesn't_ help if the parameter doesn't get used and that's the error message that comes up.

**Comment by Raveline** [comment]
Actually, it is _useful_ to be able to execute queries that don't use all their parameters.
Picture a query with many wheres, with conditional filters. You'll typically encode it in this dummy example:

```
data Filters = { filterOne :: Maybe Int
                      , filterTwo :: Maybe Bool
                      , filterThree :: Maybe String }
```

Squeal shines there because it lets you build conditionnally your query, with bits of `where` that can be added through things like `& maybe mempty (const myWhereClause) filterOne`.

However, it forces you to have different call to the `query` since not consuming every parameters fail currently, due to the problem tackled in this issue. Having a way to circumvent this would be very nice.

**Comment by echatav** [comment]
Here's what I'm thinking. Right now when `LibPQ.execParams` is getting called, it's just setting all the `Oid`s to `0`, the invalid `Oid`. Instead, we can set them using the `HasOid` typeclass. The only issue is how to set the `Oid` for user-defined types since a valid `Oid` is generated only when the type is created. Either we can set them to still be the invalid `Oid`, or we can leave them to be implemented by the user. I think the former makes more sense. It would still result in the same runtime error if you didn't use a parameter of user defined type as before, but that's still an improvement.

**Comment by Raveline** [comment]
Agreed, it sounds like a good compromise.

**Comment by echatav** [comment]
closing in favor of #163

**Pull request closed without merging**
